theme: jekyll-theme-slate
title: Learni Github Site
description: A sandbox to use whilst learning GitHub
excerpt_separator: "<!--more-->"
baseurl: "/learn/"
permalink: /:title/
# The release of Jekyll Now that you're using
version: v1.2.0
plugins:
  - jekyll-relative-links
