theme: jekyll-theme-slate
title: Learning Github Site
description: A sandbox to use whilst learning GitHub
excerpt_separator: "<!--more-->"
baseurl: "/learn/"
permalink: /:title/
# The release of Jekyll Now that you're using   
plugins:
#  - jekyll-relative-links
  
  
